import {
  ProductListing,
  Order,
  Conversation,
  DisputeTicket,
  WalletTransaction,
  UserProfile,
  BankAccount,
} from "../types";

export const SEED_SELLERS = {
  dimas: {
    id: "seller-dimas",
    name: "Dimas Aditya",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDCivYuQ1MnI7E6IupkVnB2wrdi0vZ4YEqyfTr2wFr4MaU5RbTNlZzKVLbY6mnGyFdyqX-FE0kVC8460WUMwZyEOE01o5wSIHm3BdBSMqOjiBicUzktSCRECCcm2fWwTgogLXVM-99usmt9_HZNnuqFofyCqzv1LkgmjmvKk2Re4EOV47Tt6eB8QeKSc4O8deh_Azmrwnk9_SF-A9p2wOHZXQYFmgiCIq8iIFvrTwvp_pdGJYaJOef8",
    verifiedKYC: true,
    trustScore: 98,
    rating: 4.9,
    reviewCount: 52,
    location: "Jakarta Barat",
    city: "Jakarta Barat",
    joinedDate: "Maret 2023",
    responseTime: "< 5 menit",
    successTransactions: 48,
  },
  rian: {
    id: "seller-rian",
    name: "Rian Gadget Surabaya",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuARVSFYfBWVyVsZWQluSJcL8sMPOSmnE8mGkR5BrhkwbubbuXak0j5WwkwOo1JjgKnpaf1S7WJRcRm1ZicytLS3wpBG9CPYS6LiOOXaybKow8Ho4_EogUn5YXqk4IUoQo8UdYN600NliLjnIDlOjB89sEfXd_98btgCRMHw7HE1wvgfQtQkXwX7m6c2tCpX9IqBNbnhP4Nb57GCNuHtQ2ESg9gUjeUIvzWs7RV27u5YUKcspnWFxF1e",
    verifiedKYC: true,
    trustScore: 96,
    rating: 4.9,
    reviewCount: 89,
    location: "Surabaya",
    city: "Surabaya",
    joinedDate: "Januari 2022",
    responseTime: "< 15 menit",
    successTransactions: 94,
  },
  appleholic: {
    id: "seller-appleholic",
    name: "Appleholic Store Jakarta",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuARVSFYfBWVyVsZWQluSJcL8sMPOSmnE8mGkR5BrhkwbubbuXak0j5WwkwOo1JjgKnpaf1S7WJRcRm1ZicytLS3wpBG9CPYS6LiOOXaybKow8Ho4_EogUn5YXqk4IUoQo8UdYN600NliLjnIDlOjB89sEfXd_98btgCRMHw7HE1wvgfQtQkXwX7m6c2tCpX9IqBNbnhP4Nb57GCNuHtQ2ESg9gUjeUIvzWs7RV27u5YUKcspnWFxF1e",
    verifiedKYC: true,
    trustScore: 99,
    rating: 5.0,
    reviewCount: 140,
    location: "Jakarta Selatan",
    city: "Jakarta Selatan",
    joinedDate: "Juni 2021",
    responseTime: "< 2 menit",
    successTransactions: 165,
  },
};

export const SEED_LISTINGS: ProductListing[] = [
  {
    id: "prod-sony-a7iii",
    slug: "sony-a7-iii-body-only-sc-4xxx",
    title: "Sony A7 III Body Only - SC 4xxx Mulus Dus Lengkap",
    price: 12800000,
    originalPrice: 13500000,
    category: "camera",
    categoryLabel: "Kamera",
    brand: "Sony",
    model: "ILCE-7M3",
    condition: "LIKE_NEW",
    conditionLabel: "Seperti Baru",
    conditionScore: 98,
    canNego: true,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBA9eU2ewnWRCf9Qto6GOxaOS5X8o-02N4RqCpowftk7HpYZ_uYsPQNcN97v4sr4MJfr95_S4fVUvl9q-rBghLePBKSczep7xPDx_JKdKpoeM7Lyf0yAn7Iooah63Jn2if8IUDjfHczoXbNpUY3h9xrpGA-i0uqFo6J4t0cqGiWZD3PIqT1xQNYNOh0rH_DgLS1dZ-x-VFnpFMUNWV9yKfNyLePCfnQZXHna6dkqEWvPuzEw_ah9Vgr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDJWMeK1Ph2zTUSxHLsMHXOVwJ0dsiVqZnZintraxtqMMDrQrOuJQWK0HXe8_UnQx-tirVqsoqqS6xCARvWDvARUnQYoP5GFtS5DEYRLfsnEXoF90oyqu5AYHduuYqD16r92550myGVgV1Ta8M_xaZZLjcaItLOCv9MuMWQ3JqCA2N9ytpgy0-xHGZqFcKmvGZOpJI7-DnrTVKjVonur27t8zjHo30R13YY7I48e-2eXbJN9mw56it4",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAhvM3DxYqJXa0NQAozFqVxVPSNPy7kTq9CUtMVHdNvHEw0xKdi1XssnuJZg4CUB-FnyCx4vr2k1sPXd6lvdPGm-ctwvT8QwCZeWiu7WHsi2EJvjUtN5ZsEpe4nMG5cN2BZimdKmVbxiKibuc_lAABzsykz0eH0LbLnUfY3Jz4XXGnfwS8Q9zpKKZMdg4PvBjtyWNNnpVrkUe3Qccym_vPoffDI0X0I0O_hWYd7piKSf3T-WPgrP0M_",
    ],
    location: "Gubeng, Surabaya",
    city: "Surabaya",
    description:
      "Dijual kamera Sony A7 III kesayangan pemakaian hobi pribadi. Shutter Count baru 4.120 jepretan (sangat minim, umur sensor masih super panjang). Sensor bersih kinclong tanpa debu mikro/jamur. Karet handgrip rapat kencang tanpa melar sama sekali. Layar LCD terpasang anti-gores sejak unboxing. Garansi resmi Sony Indonesia sudah habis, fungsi 100% normal tanpa kendala.",
    specifications: {
      Sensor: "24.2 MP Full-Frame Exmor R BSI CMOS",
      "Shutter Count": "4.120 Actuations (Terverifikasi)",
      "Baterai Health": "Normal 100% (NP-FZ100 Original)",
      Video: "4K 30fps HDR & 1080p 120fps Slow-mo",
      Mount: "Sony E-Mount",
    },
    completeness: [
      "Body Kamera Sony A7 III",
      "Box Original & Buku Manual",
      "Baterai Original Sony NP-FZ100",
      "Strap Asli Belum Pernah Dipakai",
      "Kabel & Adaptor Charger",
      "Kartu Garansi Sony Indonesia",
    ],
    diagnosticPassed: true,
    diagnosticTool: "Sony ShutterCount Verified (4.120)",
    seller: SEED_SELLERS.rian,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    viewsCount: 249,
    favoritesCount: 38,
    isPromoted: true,
  },
  {
    id: "prod-ipad-air5",
    slug: "ipad-air-5-64gb-wifi-starlight",
    title: "iPad Air 5 64GB WiFi Starlight - Garansi iBox On",
    price: 7500000,
    originalPrice: 8200000,
    category: "laptop",
    categoryLabel: "Tablet",
    brand: "Apple",
    model: "iPad Air 5 (M1)",
    condition: "LIKE_NEW",
    conditionLabel: "Mulus 98%",
    conditionScore: 98,
    canNego: true,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBSoZCjbay2vGyuL9c5V0UuS6ISwubNTs8UxDSQ3Xy8XNOiTohn8FkRTnn0bifNv1Y6Pkt-UtUzUwYeYbPdrIWn-YFaenC0ZI9evxtIQeyfcdDjMBpJE6o3fE21Z6pVJCIV2ki2FPpIAq_t3hJB6M-qFQUSfsUoEYznHD6Ev9G2mfo1pBtPdxzPcszriZdm8MqsmdXwXsd5lACzUJLH7keI9djL1_K6IXMoo5gCo8hizXKsoStJjm1h",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAlbpPzbHjOZiSoCv0_U4dYHqpJufGFpLVzrWBf2mmxd9iPP2XTgW5n376JZNxhO8hzgVfHzccltMxBeKKp7WBb6bypX2yY1yQEoaZz-cXWc75yNPUuS1A6Cz_me5Jr9LcsjFQIm5GCHAxFCbBXkVYn94veaZmlz0Rhx7hXnZktF2iCyKPKeubQz89fYKNU1077usOkwXqdGbT5V2VpQTtYI4V9tKCOrR8FJw8hIxNYjy6n-byCdVA9",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCjgviysQIAwDZiQ0XoEZvodqrHaDDPNayXxcGbwgx608LfwIXqUxS_WII7yj6enbMiQmCzrkAxvmRfSGkB8CDpuk_U716Nz41oHEWJJWsW-w_cnfNJZcuKmrtGQLQRZvR8edDK3huf4AZHPk4xaRAzUdRJI5OgTpKTXRZPPYqtiSVQz8cEztEGIteVkgS0qPcesQhpA-2Tv_29kxSrXpn1ZH4EJrO-I5jfZuiS1afjn1rSH8mPis_c",
    ],
    location: "Kebon Jeruk, Jakarta Barat",
    city: "Jakarta Barat",
    description:
      "Dijual santai iPad Air 5 Apple Silicon M1 warna Starlight mewah. Pembelian resmi iBox Central Park, nota fisik masih ada. Battery health di 3uTools tercatat 96% cycle count 84 wajar. Tidak pernah jatuh, tidak ada dent, layar mulus tanpa gores karena terpasang tempered glass dari hari pertama. iCloud aman siap reset di tempat.",
    specifications: {
      Chipset: "Apple M1 8-Core CPU 8-Core GPU",
      RAM: "8GB Unified Memory",
      Storage: "64GB NVMe",
      Layar: "10.9 inch Liquid Retina Display TrueTone",
      "Battery Health": "96% (3uTools Score 100)",
    },
    completeness: [
      "iPad Air 5 Starlight Unit",
      "Dus Box Original Nomor Seri Tembus",
      "Kabel Original USB-C to USB-C",
      "Adaptor 20W USB-C Apple Original",
      "Nota Pembelian Resmi iBox",
    ],
    diagnosticPassed: true,
    diagnosticTool: "3uTools 100% Passed (BH 96%)",
    seller: SEED_SELLERS.dimas,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    viewsCount: 412,
    favoritesCount: 76,
    isPromoted: true,
  },
  {
    id: "prod-macbook-m1",
    slug: "macbook-air-m1-256gb-space-grey",
    title: "MacBook Air M1 256GB Space Grey - Fullset Like New 99%",
    price: 8450000,
    originalPrice: 9200000,
    category: "laptop",
    categoryLabel: "Laptop",
    brand: "Apple",
    model: "MacBook Air M1 2020",
    condition: "LIKE_NEW",
    conditionLabel: "Seperti Baru 99%",
    conditionScore: 99,
    canNego: false,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB5AGlNW65v3aI0R4CrWZx64XEhcC9SCu6VYiQ7tk34hxG3vTLqNi6esOWfrCtIVWrFBhKvjo-mUPlTy1ytbnrP5B4jx3SfpmVpA0b9YJOUjDo-m92ptsOn4f-Q0fAOgkw4AwSG3hayF3hpXcawQOC9S59fm-bHYie6x-K3ctgzgNWMlrtH3ZDPWp8AZJCFCtnFMVcuXIRIVCAdyd6L0q40Lork3L5D_wKDNemifKRwMTJia9bCOGK6",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBkWG7Sz_sUpraniQ69WX24MQTgqzorNsedCM66Z-sAMVmJbe_erxsIGGuTRROnbNvph-GsH2BZ7rnMOL7FSTITdrGVQo8_U6GEm6QBSHAF1q7pSumvADjrnkgttEQ6UKQNOypMwiGv3NlE_6tw9gMw-V-d8otWmEQRmrBw-LyTETWOdynPL-0hvHzF4RC-z_2q3ATU_A85QDbaqBhFXkP5kgeO-LiWi0f1SIilqhPyllSbhDkIpeRD",
    ],
    location: "Tebet, Jakarta Selatan",
    city: "Jakarta Selatan",
    description:
      "MacBook Air M1 warna Space Grey kondisi istimewa super mulus 99%. Jarang dibawa keluar rumah, body dipasang skin guard sejak beli. Battery health 94% Cycle Count 68. Keyboard empuk, backlight rata, trackpad responsif, TrueTone aktif. Cocok buat coding, desain Canva/Figma, dan kantoran baterai awet 14 jam.",
    specifications: {
      Processor: "Apple Silicon M1 8-Core",
      RAM: "8GB Unified Memory",
      SSD: "256GB Superfast PCIe",
      Battery: "BH 94% (CC 68)",
      Keyboard: "US Layout Magic Keyboard",
    },
    completeness: [
      "MacBook Air M1 Unit",
      "Dus Box Original + Apple Sticker",
      "Adaptor 30W USB-C Apple",
      "Kabel USB-C 2M Original",
    ],
    diagnosticPassed: true,
    diagnosticTool: "Apple Diagnostics Passed (No issues)",
    seller: SEED_SELLERS.appleholic,
    createdAt: new Date(Date.now() - 36000000).toISOString(),
    viewsCount: 680,
    favoritesCount: 110,
    isPromoted: false,
  },
  {
    id: "prod-iphone-13pro",
    slug: "apple-iphone-13-pro-128gb-sierra-blue",
    title: "Apple iPhone 13 Pro 128GB Sierra Blue - iBox BH 88%",
    price: 9800000,
    originalPrice: 10500000,
    category: "smartphone",
    categoryLabel: "Smartphone",
    brand: "Apple",
    model: "iPhone 13 Pro",
    condition: "NORMAL_USE",
    conditionLabel: "Pemakaian Wajar 95%",
    conditionScore: 95,
    canNego: true,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuC-gWe99LzGnxTQdFSIA-zhynswki8_TgVepWWogk0dPr-cudyQwj_NeYD-28WilZwCMljHSMh_ypaxQ65sE14s01j4VVB4uYTPZzmyNu6lNxnWarYrNtyt6pPLHg4MLmL7CRMfCxzN4XNfHyu243hI6vjXKIFuZXuYgt7U-oQTSr-NpJUyB48xtXdcf8HwVjHTwtrb3cWx2FLen3dfPplDmzV8P4EjxorMDCD4vnY_nZpn5qnIVfIR",
    ],
    location: "Kuningan, Jakarta Selatan",
    city: "Jakarta Selatan",
    description:
      "Dijual iPhone 13 Pro 128GB varian warna Sierra Blue paling dicari. Region resmi Indonesia PA/A iBox sinyal permanen anti blokir seumur hidup. 3uTools hijau semua skor 98. Layar ProMotion 120Hz mulus tanpa scratch, True Tone, Face ID aktif normal. Baterai health original 88% masih awet seharian.",
    specifications: {
      Chipset: "A15 Bionic 6-Core",
      Layar: "6.1 inch Super Retina XDR ProMotion 120Hz",
      Storage: "128GB",
      "Battery Health": "88% Original (Belum pernah ganti)",
      Kamera: "Triple 12MP Telephoto + Wide + Ultra Wide",
    },
    completeness: [
      "Unit iPhone 13 Pro Sierra Blue",
      "Dus Original Sesuai IMEI",
      "Kabel Original Type-C to Lightning",
      "SIM Ejector & Booklet",
    ],
    diagnosticPassed: true,
    diagnosticTool: "3uTools Skor 98 Hijau Semua",
    seller: SEED_SELLERS.appleholic,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    viewsCount: 890,
    favoritesCount: 145,
    isPromoted: true,
  },
  {
    id: "prod-thinkpad-x1",
    slug: "lenovo-thinkpad-x1-carbon-gen-9-i7",
    title: "Lenovo ThinkPad X1 Carbon Gen 9 Core i7 16GB 512GB",
    price: 11200000,
    originalPrice: 12500000,
    category: "laptop",
    categoryLabel: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 9",
    condition: "LIKE_NEW",
    conditionLabel: "Seperti Baru",
    conditionScore: 97,
    canNego: true,
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Coblong, Bandung",
    city: "Bandung",
    description:
      "Laptop flagship bisnis tertipis dan terkuat. Body carbon fiber mulus tanpa baret. Processor Intel Core i7-1165G7 generasi ke-11 dengan RAM 16GB LPDDR4x dan SSD NVMe 512GB. Keyboard ThinkPad legendaris empuk sekali, TrackPoint presisi, sensor fingerprint aktif. Baterai tahan 10 jam kerja.",
    specifications: {
      Processor: "Intel Core i7-1165G7 Turbo Boost 4.7GHz",
      RAM: "16GB LPDDR4x 4266MHz",
      Storage: "512GB PCIe Gen4 NVMe SSD",
      Layar: "14.0 inch WUXGA (1920 x 1200) IPS Anti-glare",
      Bobot: "1.13 kg",
    },
    completeness: [
      "ThinkPad X1 Carbon Gen 9",
      "Charger Original 65W USB-C GaN",
      "Kardus Lenovo Resmi",
    ],
    diagnosticPassed: true,
    diagnosticTool: "Lenovo Vantage Hardware Test 100% Passed",
    seller: SEED_SELLERS.rian,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    viewsCount: 190,
    favoritesCount: 42,
    isPromoted: false,
  },
  {
    id: "prod-rtx-3070ti",
    slug: "asus-tuf-gaming-geforce-rtx-3070-ti-8gb",
    title: "ASUS TUF Gaming GeForce RTX 3070 Ti 8GB GDDR6X",
    price: 5800000,
    originalPrice: 6500000,
    category: "pc-gaming",
    categoryLabel: "PC Gaming",
    brand: "ASUS",
    model: "TUF-RTX3070TI-O8G-GAMING",
    condition: "NORMAL_USE",
    conditionLabel: "Pemakaian Wajar",
    conditionScore: 96,
    canNego: true,
    images: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Mangga Dua, Jakarta Pusat",
    city: "Jakarta Pusat",
    description:
      "Dijual VGA bekas pemakaian gaming pribadi (Dota 2 & Cyberpunk). Bukan bekas mining kripto! Segel baut utuh belum pernah bongkar/repaste. Suhu FurMark full load adem 67°C fan speed 55%. Tidak ada coil whine. Dus book kartu garansi Asus (sudah habis masa garansi).",
    specifications: {
      VRAM: "8GB GDDR6X 256-bit",
      "Boost Clock": "1815 MHz (OC Mode)",
      "Power Connector": "2 x 8-pin (Rekomendasi PSU 750W)",
      Suhu: "67°C Stress Test FurMark 30 Min",
    },
    completeness: ["Unit VGA Card ASUS TUF", "Box Original", "Karton & Antistatik Bag"],
    diagnosticPassed: true,
    diagnosticTool: "3DMark TimeSpy Passed (Stress 99.2%)",
    seller: SEED_SELLERS.dimas,
    createdAt: new Date(Date.now() - 129600000).toISOString(),
    viewsCount: 350,
    favoritesCount: 82,
    isPromoted: false,
  },
  {
    id: "prod-switch-oled",
    slug: "nintendo-switch-oled-white-fullset",
    title: "Nintendo Switch OLED White Fullset Box - Mulus Siap Main",
    price: 3650000,
    originalPrice: 4000000,
    category: "console",
    categoryLabel: "Konsol",
    brand: "Nintendo",
    model: "Switch OLED White",
    condition: "LIKE_NEW",
    conditionLabel: "Seperti Baru",
    conditionScore: 98,
    canNego: true,
    images: [
      "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Depok, Jawa Barat",
    city: "Depok",
    description:
      "Dijual Nintendo Switch OLED warna Putih. Pemakaian apik tangan pertama, layar OLED 7 inch bebas burn-in, sudah terpasang tempered glass Spigen. Joy-Con kencang tanpa drift sama sekali. Baterai awet normal. Kelengkapan fullset original sesuai bawaan toko.",
    specifications: {
      Layar: "7.0 inch OLED Multi-Touch",
      Storage: "64GB Internal + Slot MicroSD",
      Audio: "Enhanced Audio Stereo Speakers",
      Kondisi: "OFW Resmi (Bebas Banned)",
    },
    completeness: [
      "Nintendo Switch Console OLED",
      "Joy-Con Left & Right White",
      "Docking OLED Putih dengan Port LAN",
      "Joy-Con Grip & Strap",
      "Adaptor AC Charger Original",
      "Kabel High Speed HDMI",
      "Dus Box Original",
    ],
    diagnosticPassed: true,
    diagnosticTool: "Joy-Con Calibration & Display Test OK",
    seller: SEED_SELLERS.rian,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    viewsCount: 512,
    favoritesCount: 95,
    isPromoted: true,
  },
  {
    id: "prod-airpods-pro2",
    slug: "apple-airpods-pro-gen-2-type-c",
    title: "Apple AirPods Pro Gen 2 USB-C - Garansi iBox Aktif",
    price: 2450000,
    originalPrice: 3200000,
    category: "audio",
    categoryLabel: "Audio",
    brand: "Apple",
    model: "AirPods Pro 2 (USB-C)",
    condition: "LIKE_NEW",
    conditionLabel: "Seperti Baru 99%",
    conditionScore: 99,
    canNego: false,
    images: [
      "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Kelapa Gading, Jakarta Utara",
    city: "Jakarta Utara",
    description:
      "AirPods Pro Gen 2 versi Type-C resmi iBox pembelian November 2024 (garansi resmi masih aktif). Active Noise Cancellation (ANC) dan Transparency Mode berfungsi sempurna. Eartips cadangan ukuran XS, S, L masih utuh di box belum pernah disentuh.",
    specifications: {
      Port: "USB-C MagSafe Charging Case with Speaker",
      Chip: "Apple H2 Headphone Chip",
      Fitur: "Adaptive Audio, ANC 2x lebih senyap, Spatial Audio",
    },
    completeness: [
      "AirPods Pro 2 Earbuds L & R",
      "MagSafe Charging Case (USB-C)",
      "Set Eartips Cadangan Lengkap",
      "Kabel USB-C Braided Original",
      "Box & Kartu Garansi iBox",
    ],
    diagnosticPassed: true,
    diagnosticTool: "Coverage Apple Terverifikasi Aktif",
    seller: SEED_SELLERS.appleholic,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    viewsCount: 620,
    favoritesCount: 130,
    isPromoted: false,
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: "STX-2026-88421",
    listing: SEED_LISTINGS[1], // iPad Air 5
    buyerId: "user-budi",
    buyerName: "Budi Pratama",
    buyerPhone: "0812-8921-4432",
    shippingAddress:
      "Jl. Mawar Asri No. 18, RT 04/RW 02, Pondok Kelapa, Duren Sawit, Jakarta Timur 13450",
    itemPrice: 6900000, // Negotiated price
    shippingFee: 22000,
    escrowFee: 0, // Promo Launching
    totalAmount: 6922000,
    paymentMethod: "BCA_VA",
    vaNumber: "8277081234567890",
    status: "INSPECTING",
    paymentExpiresAt: new Date(Date.now() - 86400000).toISOString(),
    inspectionExpiresAt: new Date(Date.now() + 138000000).toISOString(), // ~38 hours remaining
    courier: "J&T Express VIP",
    trackingNumber: "JT928174829102",
    shippedAt: new Date(Date.now() - 172800000).toISOString(),
    deliveredAt: new Date(Date.now() - 34560000).toISOString(),
    createdAt: new Date(Date.now() - 200000000).toISOString(),
  },
  {
    id: "STX-2026-0701",
    listing: SEED_LISTINGS[2], // MacBook Air M1
    buyerId: "user-budi",
    buyerName: "Budi Pratama",
    buyerPhone: "0812-8921-4432",
    shippingAddress:
      "Jl. Mawar Asri No. 18, RT 04/RW 02, Pondok Kelapa, Duren Sawit, Jakarta Timur 13450",
    itemPrice: 8450000,
    shippingFee: 25000,
    escrowFee: 0,
    totalAmount: 8475000,
    paymentMethod: "BCA_VA",
    vaNumber: "8277081234567891",
    status: "DISPUTED",
    paymentExpiresAt: new Date(Date.now() - 120000000).toISOString(),
    courier: "JNE YES",
    trackingNumber: "JNE0192837482",
    shippedAt: new Date(Date.now() - 100000000).toISOString(),
    deliveredAt: new Date(Date.now() - 50000000).toISOString(),
    disputeId: "DSP-2026-88421",
    createdAt: new Date(Date.now() - 150000000).toISOString(),
  },
  {
    id: "STX-2026-1049",
    listing: SEED_LISTINGS[0], // Sony A7 III
    buyerId: "user-budi",
    buyerName: "Budi Pratama",
    buyerPhone: "0812-8921-4432",
    shippingAddress:
      "Jl. Mawar Asri No. 18, RT 04/RW 02, Pondok Kelapa, Duren Sawit, Jakarta Timur 13450",
    itemPrice: 12800000,
    shippingFee: 35000,
    escrowFee: 0,
    totalAmount: 12835000,
    paymentMethod: "BCA_VA",
    vaNumber: "8277081234567892",
    status: "PENDING_PAYMENT",
    paymentExpiresAt: new Date(Date.now() + 82800000).toISOString(), // ~23 hours
    courier: "SiCepat BEST",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "STX-2026-0932",
    listing: SEED_LISTINGS[3], // iPhone 13 Pro
    buyerId: "user-budi",
    buyerName: "Budi Pratama",
    buyerPhone: "0812-8921-4432",
    shippingAddress:
      "Jl. Mawar Asri No. 18, RT 04/RW 02, Pondok Kelapa, Duren Sawit, Jakarta Timur 13450",
    itemPrice: 9800000,
    shippingFee: 20000,
    escrowFee: 0,
    totalAmount: 9820000,
    paymentMethod: "QRIS",
    vaNumber: "QRIS-ID-88492019",
    status: "FUNDED",
    paymentExpiresAt: new Date(Date.now() - 20000000).toISOString(),
    courier: "J&T Express",
    createdAt: new Date(Date.now() - 24000000).toISOString(),
  },
  {
    id: "STX-2026-0811",
    listing: SEED_LISTINGS[7], // AirPods Pro 2
    buyerId: "user-budi",
    buyerName: "Budi Pratama",
    buyerPhone: "0812-8921-4432",
    shippingAddress:
      "Jl. Mawar Asri No. 18, RT 04/RW 02, Pondok Kelapa, Duren Sawit, Jakarta Timur 13450",
    itemPrice: 2450000,
    shippingFee: 15000,
    escrowFee: 0,
    totalAmount: 2465000,
    paymentMethod: "BCA_VA",
    vaNumber: "8277081234567893",
    status: "COMPLETED",
    paymentExpiresAt: new Date(Date.now() - 300000000).toISOString(),
    courier: "JNE REG",
    trackingNumber: "JNE8829102910",
    shippedAt: new Date(Date.now() - 280000000).toISOString(),
    deliveredAt: new Date(Date.now() - 200000000).toISOString(),
    completedAt: new Date(Date.now() - 180000000).toISOString(),
    reviewGiven: true,
    createdAt: new Date(Date.now() - 320000000).toISOString(),
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: "convo-dimas-ipad",
    listingId: "prod-ipad-air5",
    listing: SEED_LISTINGS[1],
    counterpart: SEED_SELLERS.dimas,
    lastMessage: "Harga penawarannya sudah saya acc ya kak! Siap di-packing bubble wrap tebal.",
    lastTimestamp: new Date(Date.now() - 120000).toISOString(),
    unreadCount: 1,
    messages: [
      {
        id: "msg-1",
        senderId: "user-budi",
        senderName: "Budi Pratama",
        text: "Halo mas Dimas, iPad Air 5-nya masih ada? Baterai health di 3uTools berapa persen ya? Charger bawaan 20W masih lengkap?",
        timestamp: "14:21",
        isRead: true,
      },
      {
        id: "msg-2",
        senderId: "seller-dimas",
        senderName: "Dimas Aditya",
        text: "Halo kak! Masih ready banget. BH 96% cycle count 84 wajar. Dus, kabel Type-C asli & adaptor 20W lengkap ada nota pembelian iBox juga. Layar terpasang tempered glass dari hari pertama.",
        timestamp: "14:22",
        isRead: true,
      },
      {
        id: "msg-3",
        senderId: "user-budi",
        senderName: "Budi Pratama",
        text: "Keren mas. Kalau saya tawar Rp 6.900.000 via Rekber Escrow langsung saya checkout sekarang, gimana?",
        timestamp: "14:23",
        isRead: true,
        offer: {
          id: "offer-1",
          listingId: "prod-ipad-air5",
          buyerId: "user-budi",
          sellerId: "seller-dimas",
          originalPrice: 7500000,
          offerPrice: 6900000,
          discountPercent: 8,
          status: "ACCEPTED",
          expiresAt: new Date(Date.now() + 86400000).toISOString(),
          checkoutWindowExpiresAt: new Date(Date.now() + 7200000).toISOString(),
        },
      },
      {
        id: "msg-4",
        senderId: "seller-dimas",
        senderName: "Dimas Aditya",
        text: "Harga penawarannya sudah saya acc ya kak! Siap di-packing bubble wrap tebal + kardus pelindung double. Silakan di-checkout via rekber.",
        timestamp: "14:26",
        isRead: false,
      },
    ],
  },
  {
    id: "convo-rian-sony",
    listingId: "prod-sony-a7iii",
    listing: SEED_LISTINGS[0],
    counterpart: SEED_SELLERS.rian,
    lastMessage: "Bisa kak, silakan diajukan penawarannya di fitur Nego ya.",
    lastTimestamp: new Date(Date.now() - 3600000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "msg-s1",
        senderId: "user-budi",
        senderName: "Budi Pratama",
        text: "Malam mas Rian, Sony A7 III sensornya bebas jamur ya? Boleh nego tipis nggak?",
        timestamp: "20:10",
        isRead: true,
      },
      {
        id: "msg-s2",
        senderId: "seller-rian",
        senderName: "Rian Gadget Surabaya",
        text: "Malam kak Budi! Sensor 100% bersih kinclong, selalu simpan di dry cabinet. Boleh kak, silakan diajukan penawarannya di fitur Nego ya.",
        timestamp: "20:15",
        isRead: true,
      },
    ],
  },
];

export const SEED_DISPUTE: DisputeTicket = {
  id: "DSP-2026-88421",
  orderId: "STX-2026-0701",
  listingTitle: "MacBook Air M1 256GB Space Grey",
  listingPrice: 8450000,
  listingImage:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuB5AGlNW65v3aI0R4CrWZx64XEhcC9SCu6VYiQ7tk34hxG3vTLqNi6esOWfrCtIVWrFBhKvjo-mUPlTy1ytbnrP5B4jx3SfpmVpA0b9YJOUjDo-m92ptsOn4f-Q0fAOgkw4AwSG3hayF3hpXcawQOC9S59fm-bHYie6x-K3ctgzgNWMlrtH3ZDPWp8AZJCFCtnFMVcuXIRIVCAdyd6L0q40Lork3L5D_wKDNemifKRwMTJia9bCOGK6",
  buyerName: "Budi Pratama",
  sellerName: "Dimas Aditya",
  reason: "Barang Tidak Sesuai Deskripsi (Goresan Layar Tipis)",
  description:
    "Halo admin, saat paket dibuka dan dites di bawah cahaya ruangan, ada goresan mikro sepanjang 3cm di sudut kanan atas layar yang tidak diinfokan di deskripsi listing (dibilang mulus 99%). Video unboxing lengkap sudah diunggah.",
  buyerEvidencePhotos: [
    "https://lh3.googleusercontent.com/aida-public/AB6AXuBkWG7Sz_sUpraniQ69WX24MQTgqzorNsedCM66Z-sAMVmJbe_erxsIGGuTRROnbNvph-GsH2BZ7rnMOL7FSTITdrGVQo8_U6GEm6QBSHAF1q7pSumvADjrnkgttEQ6UKQNOypMwiGv3NlE_6tw9gMw-V-d8otWmEQRmrBw-LyTETWOdynPL-0hvHzF4RC-z_2q3ATU_A85QDbaqBhFXkP5kgeO-LiWi0f1SIilqhPyllSbhDkIpeRD",
  ],
  sellerEvidencePhotos: [
    "https://lh3.googleusercontent.com/aida-public/AB6AXuB5AGlNW65v3aI0R4CrWZx64XEhcC9SCu6VYiQ7tk34hxG3vTLqNi6esOWfrCtIVWrFBhKvjo-mUPlTy1ytbnrP5B4jx3SfpmVpA0b9YJOUjDo-m92ptsOn4f-Q0fAOgkw4AwSG3hayF3hpXcawQOC9S59fm-bHYie6x-K3ctgzgNWMlrtH3ZDPWp8AZJCFCtnFMVcuXIRIVCAdyd6L0q40Lork3L5D_wKDNemifKRwMTJia9bCOGK6",
  ],
  slaExpiresAt: new Date(Date.now() + 160000000).toISOString(),
  status: "INVESTIGATING",
  messages: [
    {
      id: "disp-1",
      author: "Budi Pratama",
      role: "BUYER",
      text: "Saya mengajukan komplain retur dana / partial refund karena goresan layar ini mengurangi nilai jual gadget.",
      timestamp: "Kemarin, 16:40 WIB",
    },
    {
      id: "disp-2",
      author: "Dimas Aditya",
      role: "SELLER",
      text: "Halo mas Budi & admin. Sebelum kirim saya rekam video QC packing dan layar dalam keadaan mulus. Kemungkinan gores terjadi akibat gesekan debu saat kurir membuka atau handling pembeli.",
      timestamp: "Kemarin, 18:20 WIB",
    },
    {
      id: "disp-3",
      author: "Admin NgeBekasinYuk",
      role: "ADMIN",
      text: "Tim mediasi sedang menelaah video unboxing dan rekaman QC packing seller. Keputusan SLA mediasi maksimal 2x24 jam.",
      timestamp: "Hari ini, 09:00 WIB",
    },
  ],
};

export const SEED_WALLET_TRANSACTIONS: WalletTransaction[] = [
  {
    id: "TRX-W-9921",
    type: "ESCROW_RELEASE",
    amount: 2450000,
    referenceId: "STX-2026-0811",
    status: "SUCCESS",
    timestamp: "10 Sep 2026, 14:30 WIB",
    description: "Pencairan dana pesanan AirPods Pro Gen 2",
  },
  {
    id: "TRX-W-9890",
    type: "WITHDRAWAL",
    amount: 5000000,
    referenceId: "WD-2026-0909",
    status: "SUCCESS",
    timestamp: "09 Sep 2026, 10:15 WIB",
    description: "Penarikan saldo ke Rekening BCA (****8920)",
  },
  {
    id: "TRX-W-9840",
    type: "ESCROW_RELEASE",
    amount: 11800000,
    referenceId: "STX-2026-0775",
    status: "SUCCESS",
    timestamp: "05 Sep 2026, 18:45 WIB",
    description: "Pencairan dana pesanan iPhone 14 128GB",
  },
  {
    id: "TRX-W-9799",
    type: "ESCROW_HOLD",
    amount: 6900000,
    referenceId: "STX-2026-88421",
    status: "PENDING",
    timestamp: "Hari ini, 14:26 WIB",
    description: "Dana tertahan di Escrow (iPad Air 5 - Masa Inspeksi)",
  },
];

export const SEED_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: "bank-1",
    bankName: "BCA (Bank Central Asia)",
    accountNumber: "8277081234",
    accountHolder: "Budi Pratama",
    isPrimary: true,
  },
  {
    id: "bank-2",
    bankName: "Bank Mandiri",
    accountNumber: "1370008892110",
    accountHolder: "Budi Pratama",
    isPrimary: false,
  },
];

export const SEED_USER: UserProfile = {
  id: "user-budi",
  name: "Budi Pratama",
  email: "budi.pratama@techmail.id",
  phone: "0812-8921-4432",
  avatar:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDCivYuQ1MnI7E6IupkVnB2wrdi0vZ4YEqyfTr2wFr4MaU5RbTNlZzKVLbY6mnGyFdyqX-FE0kVC8460WUMwZyEOE01o5wSIHm3BdBSMqOjiBicUzktSCRECCcm2fWwTgogLXVM-99usmt9_HZNnuqFofyCqzv1LkgmjmvKk2Re4EOV47Tt6eB8QeKSc4O8deh_Azmrwnk9_SF-A9p2wOHZXQYFmgiCIq8iIFvrTwvp_pdGJYaJOef8",
  isKYCVerified: true,
  trustScore: 92,
  joinedDate: "Februari 2024",
  addresses: [
    {
      id: "addr-1",
      label: "Rumah (Utama)",
      recipientName: "Budi Pratama",
      phone: "0812-8921-4432",
      addressLine: "Jl. Mawar Asri No. 18, RT 04/RW 02, Pondok Kelapa, Duren Sawit",
      city: "Jakarta Timur",
      postalCode: "13450",
      isDefault: true,
    },
    {
      id: "addr-2",
      label: "Kantor / Kosan",
      recipientName: "Budi Pratama",
      phone: "0812-8921-4432",
      addressLine: "Jl. Dipati Ukur No. 45, Lebakgede, Coblong",
      city: "Bandung",
      postalCode: "40132",
      isDefault: false,
    },
  ],
  favorites: ["prod-sony-a7iii", "prod-ipad-air5"],
};
